### ISSUE TITLE
Add [yajl parse] command

### ISSUE THREAD

**Issue by bradennapier** [flightaware/yajl-tcl#26]
As stated as the only solution to https://github.com/flightaware/yajl-tcl/issues/21 (which i still think needs a better solution/option for edge cases), the parse method would be the only way to handle this. 

Based on what [$json parse] does, I would thin kit makes sense to expose the command without first creating an object.  It doesn't seem to affect the actual object itself and takes a normal json value so in that sense I would propose

```tcl
set parsed [yajl parse {{"one": "two"}}]
```

as an option to parse the json even when you have no need at that time for an actual yajl object.

**Comment by bovine** [comment]
Your proposal is that it is just a static method by not requiring an object reference, and it produces the same output as this?:

    set object [yajl create #auto]
    set parsed [$object parse {{"one": "two"}}]
    $object delete

**Comment by bradennapier** [comment]
Correct.  In my case I mesh the benefits of `rl_json` with yajltcl.  I will often then saved the "mapped" version of the json so I find myself doing what you show there quite often.  

It seems that since [parse] does not actually do anything with the yajl object itself that it makes sense that it would be a static method of [yajl] rather than of the instance.  

My logic may be off - but your solution in #21 actually showed using it as a static method as well ;-)

**Comment by bovine** [comment]
I didn't actually test my sample code in that other issue, so that is why it incorrectly showed it as a static method. That was not intentional nor indicative of this functionality already existing.

The original reason that the parse method was not originally a static method is that there is a fair bit of other locally allocated data that is associated with the parsers. I think it is also possible to parse a large JSON buffer incrementally by calling the parse method with the data you have and then calling "$object parse_complete" when done.

It looks like there would be a fair amount of code refactoring in order to make it a static method. Because there are actually several parser commands ("parse", "parse2dict", "parse2huddle") those others would probably make sense to be treated in the same way.

If you're doing a lot of parsing, it would probably provide better performance to create a global yajltcl object and simply reuse it to invoke its parse method whenever you need it.

**Comment by bradennapier** [comment]
Ok.  I opened another issue that I do believe is a bug.  I will close this one.  Thanks.
